### ISSUE TITLE
Questions regarding BOS/CHOCH function

### ISSUE THREAD

**Issue by VolodymyrZavalinskyi** [joshyattridge/smart-money-concepts#17]
Hi team,
Could you please help with some questions about **bos_choch** function:

1. What does mean **BrokenIndex** and what its value means ? (some position(candle) number; it doesn't equal the candle number in the data frame)
2. How can we show all **Level** values, not only when we have BOS or CHOCH ?
3. As I understand and can see from testing the BOS or CHOCH, the price is showing for the candle that starts the breaking price and not closes. How we can show the BOS or CHOCH but on the candle that closes the breaking.
I know that the decision is made based on the swing highs and lows but can we somehow show BOS or CHOCH on the candle which closes the price breaking even if this candle is not a swing high or low ?

**Comment by joshyattridge** [comment]
Hello @VolodymyrZavalinskyi,

Ill be happy to help with your questions.

1. BrokenIndex should be the index of the candle that breaks the High/Low
2. The bos_choch uses the highs and lows from the swing_highs_lows function so if you want to know the levels without the BOS/ChoCH then you should use the data from the swing_highs_lows function.
3. What you're saying here makes sense and I can see why you would want the indication on the candle that is breaking the High/Low. But doing it this way doesn't keep inline with the structure of all the other functions, maybe a better solution needs to be thought of to resolve this but I don't have an answer at the moment unless you have any Ideas?

Thanks for the feedback!
Josh
