### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by phpmac** [joshyattridge/smart-money-concepts#18]
```
import ccxt
import pandas as pd
from smartmoneyconcepts import smc

exchange = ccxt.binanceusdm(
    {
        "apiKey": "1",
        "secret": "1",
        "enableRateLimit": True,
    }
)

# exchange.verbose = True
exchange.options["warnOnFetchOpenOrdersWithoutSymbol"] = False

klines = exchange.fetch_ohlcv("POLYX/USDT", "1h", limit=100)

# 转为 df
df = pd.DataFrame(
    klines, columns=["timestamp", "open", "high", "low", "close", "volume"]
)

swing_highs_lows = smc.swing_highs_lows(df, 50)
print(swing_highs_lows)

# fvg_data = smc.fvg(df)
# df = pd.concat([df, fvg_data], axis=1)

# swing_highs_lows = smc.swing_highs_lows(df)
# print(swing_highs_lows)

# print(df)

```

**Comment by phpmac** [comment]
<img width="1552" alt="截屏2024-03-27 10 26 18" src="https://github.com/joshyattridge/smart-money-concepts/assets/86544347/b0cbfb4e-0774-41f9-9c75-5dfb088d25db">

**Comment by narmaku** [comment]
Hello, I have exactly the same issue.
I have tried resetting the dataframe indexes to integers, and also truncating it, but it didn't help at all.

```
...

  File "..\venv\lib\site-packages\smartmoneyconcepts\smc.py", line 34, in wrap
    return func(*args, **kwargs)
  File "..\venv\lib\site-packages\smartmoneyconcepts\smc.py", line 192, in swing_highs_lows
    if swing_highs_lows[positions[0]] == 1:
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by narmaku** [comment]
Thanks @VioletEsfenaj. I was already using iloc.

So I think the issue was the fact that I was passing a very high swing_length.

My DataFrame contains candles from the last 60 minutes (1-min candles). So I guess I need to pass a very small swing_length value. I tried with 5 and 3 and it worked well, apparently.

**Comment by joshyattridge** [comment]
This error occurs when the "swing_length" is too large for the amount of candles provided, so you will either need to reduce the "swing_length" or increase the amount of candles you provide the "swing_highs_lows" function
